### ISSUE TITLE
IE8 problem: uglified version

### ISSUE THREAD

**Issue by evilfer** [reflux/reflux-core#16]
Hi, I'm using Reflux for a project that requires support for IE8. The non-minified and minified-with-names-not-mangled versions work fine, but not if the uglifier mangles names as well.

I could track this problem down to line 54 of lib/createAction.js:

``` js
    var functor = function functor() {
```

Which differs from src/createAction.js:

``` js
    var functor = function() {
```

I'm not sure why in the lib version is different from the src version, but it seems to be too much for IE8 with mangled names. Restoring the src line inside lib/createAction.js makes Reflux work with IE8 in my case. 

I appreciate you may not be interested in supporting IE8, but still, is this something that could be 'fixed'?

**Comment by devinivy** [comment]
The lib and src versions differ due to babel.  If this is something that the reflux project cares about, it seems this could be alleviated with the jscript transformer: https://babeljs.io/docs/plugins/transform-jscript/.

I'd personally opt to not worry about IE8, given that IE users are being [nagged to upgrade](http://www.windowscentral.com/microsoft-will-prompt-ie-8-9-and-10-users-upgrade-ie-11-jan-12) as of last week.  Maybe a note could be made in the readme for steps to compile reflux-core in an IE8-compatible way.  Worth noting that IE8 is not ES5-compatible.

**Comment by spoike** [comment]
Considering my time with maintaining the project is very limited and <IE10 are now unsupported browsers, I'm not likely going to work on this issue until much much later. Help from community is greatly appreciated.

**Comment by evilfer** [comment]
I understand completely the focus on modern browsers! Wish I was there...

It seems that if the original code has a name for the function (src/createAction.js):

``` javascript
    var functor = function _functor () {
```

The babel-compiled version keeps both different names, and prevents the apparent name collision in the minimized version that breaks on IE8.

Cons: hacky and ugly code. Probably babel can be configured to solve the problem but haven't looked into that...

See: https://github.com/reflux/reflux-core/pull/20
